Sprint 2
kapitoshka808/middle.messenger.praktikum.yandex pull request #3
Opened 2022-04-10 20:10 UTC by kapitoshka808

2022-04-11 07:29 UTC, podlovchenko requested changes
Привет, в целом все хорошо) Но нужно разобраться с падающим пр чеком и добавить актуальную ссылку на netlify
Также было бы хорошо добавить страницу со списком всех ссылок

2022-04-11 07:29 UTC, podlovchenko commented on src/utils/HTTPTransport.ts
> +      headers = { 'Content-Type': 'application/json' },
Этот заголовок не нужно всегда устанавливать

2022-04-11 07:29 UTC, podlovchenko commented on src/components/form/form.ts
> +  constructor(context: TForm, events = {}) {
Для events тоже стоит указать тип

2022-04-11 16:21 UTC, kapitoshka808 commented on src/components/form/form.ts
> +  constructor(context: TForm, events = {}) {
Указал тип Object, но во время вызова конструктора присваивается необходимый тип для ивента

2022-04-11 16:23 UTC, kapitoshka808 commented
> Привет, в целом все хорошо) Но нужно разобраться с падающим пр чеком и добавить актуальную ссылку на netlify Также было бы хорошо добавить страницу со списком всех ссылок

Тест роутинга закомментировал, как советовали в Slack - тест у многих падает, хотя все работает.

2022-04-11 16:42 UTC, podlovchenko approved these changes
Принимаю работу, хорошего вечера)

2022-04-11 17:23 UTC, kapitoshka808 commented
> Принимаю работу, хорошего вечера)

Спасибо за ревью, всего доброго)

2022-04-11 17:24 UTC, merged

2024-04-27 06:22 UTC, endlesss-builds commented
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
jeffprestes, @MFrank2016, @tauseefk, @chreble, @honelyboy, @BowTiedSwan, @minhhoang121296, @jdgc, @dezcalimese, @OhJia, @alvarlaigna, @pynchmeister, @0xhaz, @robneal, @DecoratedWings, @magick93, @shaxzad, @ibruthecreator, @OdinMorningstar, @imagobea, @Silence1017, @GoatsefaceKilla, @d3vild06, @Formator, @jamesmorgan, @Cotspheer, @chu108, @tonydattolo, @itsstdev, @Thro77le, @wpank, @lilpolymath, @Talha-Javaid, @dec0dOS, @folathecoder, @KovacZan, @nulven, @Dmdv, @jsidorenko, @muhammadsamir11, @cryptowealth-technology, @akashiceth, @naruto3315, @nowherekai, @jesperkristensen58, @tangert, @jieunyoo, @samatstaked, @samnang, @edisinovcic